### ISSUE TITLE
Google login not working at all

### ISSUE THREAD

**Issue by r0skar** [dukt/social#49]
### Description

I have installed the plugin and configured it for Google. Everything seems to work fine (there are no Google errors when using the sign-in form), however when I test it to register a new account, the login page simply reloads and does nothing else:

### Steps to reproduce

- Open the login page @ `/admin/login`
- Click on the Google icon
- The page reloads

Here is the log part:

```
$_SESSION = [
    '7d51c018d6ff8a23e8e865578a5288b5__flash' => [
        'cp-error' => -1
    ]
    'social.isCpRequest' => true
    'social.originUrl' => 'https://XXXXXXXX.lndo.site/index.php/admin/login'
    'social.redirectUrl' => null
    'social.loginProvider' => 'google'
    'social.oauth2State' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    'cp-error' => 'redirect_uri_mismatch'
]  
2022-11-07 13:17:41 [web.INFO] [yii\db\Connection::open] Opening DB connection: mysql:host=database;port=3306;dbname=XXXXXXXX {"memory":892576} 
2022-11-07 13:17:41 [web.INFO] [percipiolondon\colourswatches\ColourSwatches::init] Colour Swatches plugin loaded {"memory":1341232} 
2022-11-07 13:17:41 [web.INFO] [yii\web\Session::open] Session started {"memory":1413432} 
2022-11-07 13:17:41 [web.ERROR] [dukt\social\controllers\LoginAccountsController::actionCallback] Couldn’t login. #0 /app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\Google->checkResponse(Object(GuzzleHttp\Psr7\Response), Array)
#1 /app/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request))
#2 /app/vendor/dukt/social/src/base/LoginProvider.php(441): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\AuthorizationCode), Array)
#3 /app/vendor/dukt/social/src/base/LoginProvider.php(147): dukt\social\base\LoginProvider->oauth2Callback()
#4 /app/vendor/dukt/social/src/controllers/LoginAccountsController.php(214): dukt\social\base\LoginProvider->oauthCallback()
#5 [internal function]: dukt\social\controllers\LoginAccountsController->actionCallback()
#6 /app/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /app/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /app/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('callback', Array)
#9 /app/vendor/craftcms/cms/src/web/Application.php(301): yii\base\Module->runAction('social/login-ac...', Array)
#10 /app/vendor/craftcms/cms/src/web/Application.php(625): craft\web\Application->runAction('social/login-ac...', Array)
#11 /app/vendor/craftcms/cms/src/web/Application.php(280): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#12 /app/vendor/yiisoft/yii2/base/Application.php(384): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /app/web/index.php(26): yii\base\Application->run()
#14 {main} {"memory":1440312} 
2022-11-07 13:17:41 [web.INFO] [application] Request context:
$_GET = [
    'p' => 'actions/social/login-accounts/callback'
    'state' => 'XXXXXXXXXXXXXXXXXXXXXXXX'
    'code' => 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx'
    'scope' => 'email profile https://www.googleapis.com/auth/userinfo.email openid https://www.googleapis.com/auth/userinfo.profile'
    'authuser' => '0'
    'hd' => 'XXXXXXXX'
    'prompt' => 'none'
]
```

I am wondering why it says `redirect_uri_mismatch`, but Google itself is not throwing (if the  Authorised redirect URIs were wrong, I would expect a Google error).

### Additional info

- Plugin version:  3.0.0-beta.1
- Craft version: 4.3.1
- PHP version: 8.1.2
- Database driver & version: MYSQL
- Plugins & versions:

```
"craftcms/aws-s3": "^2.0.1",
"craftcms/redactor": "^3.0.2",
"dukt/social": "3.0.0-beta.1",
"imgix/imgix-php": "dev-main",
"percipioglobal/craft-colour-swatches": "^4.2.0.1",
"sebastianlenz/linkfield": "^2.1.4",
"spicyweb/craft-neo": "3.4.0",
"verbb/field-manager": "3.0.4",
```

**Comment by r0skar** [comment]
P.S. I have tested the same OAuth setup with https://plugins.craftcms.com/enupal-socializer and that one works (it has other problems with the baseUrl, but thats a different topic). So, I think the Google Cloud OAuth Api part is configured correctly.
